from turtle import*
speed(1)
left(90)
color ("red")
begin_fill()
color("red")
penup()
begin_fill()
right(45)
forward(200/(2**0.5))
right(90)
forward(200/(2**0.5))
right(135)
end_fill()
pendown()
color("gray")
for i in range (4):
    forward(200)
    left (90)

penup()
color("yellow")
forward (70)
left (90)
forward(35)
begin_fill()
for j in range (4):
    forward(45)
    left (90)
end_fill()
forward(70)
right (90)
forward(50)
color("blue")
begin_fill()
for k in range (2):
    forward(50)
    left(90)
    forward(95)
    left (90)
end_fill()
mainloop()